"""Tests for the configurable knobs (src/config.py) and what they must not break.

Three jobs, in descending order of how much damage their failure would do.

FIRST, PIN THE DEFAULTS
    The defaults are the graded system. README.md, DESIGN.md, EVALUATION.md and
    model_card.md all describe the behavior these exact values produce, and
    assets/ holds committed output generated under them. Making the parameters
    editable created a brand new way to invalidate every one of those documents:
    change a default while experimenting and nothing fails loudly, the numbers
    just quietly stop matching the prose. So the defaults are pinned by name and
    by value here, and the whole point is that this test is annoying to change.

SECOND, PIN THE INVARIANTS THAT MUST SURVIVE ANY CONFIGURATION
    score_song promises its reason strings sum to its score, and that promise is
    documented in the model card. It was easy to hold when the weights were the
    literals 2.0 and 1.0; it is a real constraint once a weight can be 0.35. The
    existing suite pins it at the defaults, so this file pins it at deliberately
    awkward weights (thirds, non-round multipliers) where a rounding mistake in
    the energy term has somewhere to hide.

THIRD, PIN THAT THE KNOBS ACTUALLY DO SOMETHING
    A knob that is wired to nothing is worse than no knob, because it invites a
    conclusion drawn from an experiment that never ran. Each knob gets a test
    showing it moves a measurement in the expected direction.
"""

from __future__ import annotations

from dataclasses import replace

import os
from dataclasses import FrozenInstanceError, replace

import pytest

from src.config import (
    DEFAULT_RETRIEVAL,
    DEFAULT_SCORING,
    DEFAULT_STOPWORDS,
    RetrievalConfig,
    ScoringConfig,
    describe,
    reset_to_defaults,
    retrieval_or_default,
    scoring_or_default,
)
from src.evaluate_retrieval import (
    evaluate,
    grounded_count,
    leave_one_out,
    metrics_for_config,
    render_comparison,
)
from src.recommender import load_songs, recommend_songs, score_song
from src.retriever import MIN_CONFIDENCE, load_notes, retrieve_note

DATA = os.path.join(os.path.dirname(__file__), "..", "data")


def _catalog():
    return load_songs(os.path.join(DATA, "songs.csv"))


def _notes():
    return load_notes(os.path.join(DATA, "song_notes.md"))


# ---------------------------------------------------------------------------
# 1. The defaults, pinned by value
# ---------------------------------------------------------------------------

def test_default_scoring_weights_are_two_one_one():
    """The recipe the documentation describes: genre 2.0, mood 1.0, energy 1.0.

    If this fails, someone changed the recipe. That is allowed, but it means the
    README, DESIGN, EVALUATION and model card figures are now wrong and the
    committed evidence in assets/ was generated by a system that no longer
    exists. Update those together or not at all.
    """
    assert DEFAULT_SCORING.genre_weight == 2.0
    assert DEFAULT_SCORING.mood_weight == 1.0
    assert DEFAULT_SCORING.energy_weight == 1.0


def test_default_retrieval_knobs_are_the_shipped_guardrails():
    """Floor 0.15, and all three behavioral switches ON.

    The three booleans matter more than the float. use_metadata_filter False in
    particular is a live bug (a song with no note gets explained with another
    song's facts), so it defaulting to True is a safety property, not a taste.
    """
    assert DEFAULT_RETRIEVAL.min_confidence == 0.15
    assert DEFAULT_RETRIEVAL.use_exact_title_tiebreak is True
    assert DEFAULT_RETRIEVAL.use_metadata_filter is True
    assert DEFAULT_RETRIEVAL.use_stopwords is True
    assert DEFAULT_RETRIEVAL.stopwords == DEFAULT_STOPWORDS


def test_the_documented_zero_to_four_scale_holds_at_the_defaults():
    """Max score is exactly 4.00 under the defaults, and 4.0 is not enforced.

    The scale is a CONSEQUENCE of 2.0 + 1.0 + 1.0, not a normalization step, so
    it needs pinning at the defaults precisely because it is free to move
    elsewhere. The second half of this test is the other side of that: a
    reweighted config genuinely reports a different ceiling rather than being
    quietly rescaled back to 4.0, which would hide the effect of the knob.
    """
    assert DEFAULT_SCORING.max_score == 4.0

    louder_genre = replace(DEFAULT_SCORING, genre_weight=5.0)
    assert louder_genre.max_score == 7.0


def test_a_perfect_match_scores_exactly_four_on_the_real_catalog():
    """End to end: the documented 4.00 ceiling is reachable and is the ceiling.

    Pinning the arithmetic (above) is not enough on its own, because the claim in
    the documentation is about what the SYSTEM prints for a real profile, not
    about a property of a dataclass.
    """
    songs = _catalog()
    prefs = {"favorite_genre": "pop", "favorite_mood": "happy", "target_energy": 0.80}
    ranked = recommend_songs(prefs, songs)

    top_score = ranked[0][1]
    assert top_score == pytest.approx(4.0)
    # And nothing can beat it: 4.00 is the ceiling, not merely the best on offer.
    for _song, score, _reasons in recommend_songs(prefs, songs, k=len(songs)):
        assert score <= 4.0


def test_the_module_constants_still_alias_the_defaults():
    """retriever.MIN_CONFIDENCE must not drift away from the config it mirrors.

    The constant is kept as an alias so the config refactor touched no existing
    import. An alias that silently stops matching its source is the classic way
    that convenience becomes a bug, so it gets a test.
    """
    assert MIN_CONFIDENCE == DEFAULT_RETRIEVAL.min_confidence


# ---------------------------------------------------------------------------
# 2. Invariants that must survive ANY configuration
# ---------------------------------------------------------------------------

# Deliberately awkward weights. Round numbers like 2.0 and 0.5 cannot expose a
# rounding mistake in the energy term because they divide cleanly; thirds and
# non-round multipliers can.
AWKWARD_WEIGHTS = [
    ScoringConfig(genre_weight=0.0, mood_weight=0.0, energy_weight=0.0),
    ScoringConfig(genre_weight=0.35, mood_weight=0.07, energy_weight=0.7),
    ScoringConfig(genre_weight=1 / 3, mood_weight=2 / 3, energy_weight=1 / 7),
    ScoringConfig(genre_weight=10.0, mood_weight=0.01, energy_weight=3.33),
    ScoringConfig(genre_weight=5.0, mood_weight=5.0, energy_weight=0.001),
]

# Energy pairs chosen so closeness lands on values that do not round cleanly
# (0.67, 0.33, 0.88), which is where a weight applied on the wrong side of the
# round() would show up as a mismatch of one cent.
ENERGY_PAIRS = [(0.80, 0.80), (0.17, 0.50), (0.5, 0.83), (0.12, 1.0), (0.0, 0.99)]


@pytest.mark.parametrize("config", AWKWARD_WEIGHTS)
@pytest.mark.parametrize("song_energy,target_energy", ENERGY_PAIRS)
def test_reasons_sum_to_score_under_any_weights(config, song_energy, target_energy):
    """The model card's guarantee, re-pinned across the whole weight space.

    The existing suite checks this at the default 2/1/1. That version could not
    have caught the specific bug this refactor risked, which is applying the
    energy weight AFTER rounding the closeness: at weight 1.0 the two orders are
    identical, so the default-weight test passes either way. Here a weight of
    0.7 on a closeness of 0.67 gives 0.469, and rounding on the wrong side prints
    +0.47 while adding 0.469.
    """
    song = {"title": "T", "genre": "pop", "mood": "happy", "energy": song_energy}
    prefs = {"favorite_genre": "pop", "favorite_mood": "happy",
             "target_energy": target_energy}

    score, reasons = score_song(prefs, song, config)

    # Parse the "+N" back out of each reason exactly the way glassbox does, so
    # this test also guards the Inspector's breakdown display.
    parsed = sum(float(r.rsplit("(+", 1)[1].rstrip(")")) for r in reasons)
    assert parsed == pytest.approx(score, abs=1e-12)


@pytest.mark.parametrize("config", AWKWARD_WEIGHTS)
def test_reasons_sum_to_score_when_dimensions_do_not_match(config):
    """The same guarantee on the partial-match and no-match paths.

    A non-matching dimension appends no reason at all, so the sum has to
    reconcile against a shorter list. This is the shape that would break if a
    weight were ever added to the score outside the branch that prints it.
    """
    song = {"title": "T", "genre": "metal", "mood": "calm", "energy": 0.42}
    prefs = {"favorite_genre": "pop", "favorite_mood": "happy", "target_energy": 0.80}

    score, reasons = score_song(prefs, song, config)
    parsed = sum(float(r.rsplit("(+", 1)[1].rstrip(")")) for r in reasons)
    assert parsed == pytest.approx(score, abs=1e-12)


def test_passing_no_config_is_identical_to_passing_the_defaults():
    """The "optional argument" contract, checked rather than assumed.

    Every function grew a config parameter defaulting to the module default. This
    is the test that says the default path really is the old path: if the
    fallback were ever wired to a fresh ScoringConfig() built somewhere with a
    typo'd weight, every caller that passes nothing would silently change.
    """
    songs, notes = _catalog(), _notes()
    prefs = {"favorite_genre": "pop", "favorite_mood": "happy", "target_energy": 0.80}

    for song in songs:
        assert score_song(prefs, song) == score_song(prefs, song, DEFAULT_SCORING)
        assert retrieve_note(song, notes) == retrieve_note(song, notes, DEFAULT_RETRIEVAL)

    assert recommend_songs(prefs, songs) == recommend_songs(prefs, songs,
                                                            config=DEFAULT_SCORING)


def test_retrieve_note_keeps_its_three_tuple_contract_under_every_knob():
    """The return shape is fixed even when a knob changes the answer.

    retrieve_note's (note, confidence, title) contract is relied on by
    src/explain.py, app.py and glassbox. A knob is allowed to change WHAT is
    returned and never HOW MANY things are returned.
    """
    songs, notes = _catalog(), _notes()
    song = songs[0]

    variants = [DEFAULT_RETRIEVAL] + [cfg for _label, cfg in _variant_configs()]
    for config in variants:
        result = retrieve_note(song, notes, config)
        assert isinstance(result, tuple) and len(result) == 3
        note, confidence, title = result
        assert note is None or isinstance(note, str)
        assert 0.0 <= confidence <= 1.0
        assert title is None or isinstance(title, str)


def _variant_configs() -> list[tuple[str, RetrievalConfig]]:
    """One config per retrieval knob, each one field away from the defaults."""
    return [
        ("no tiebreak", replace(DEFAULT_RETRIEVAL, use_exact_title_tiebreak=False)),
        ("no stopwords", replace(DEFAULT_RETRIEVAL, use_stopwords=False)),
        ("high floor", replace(DEFAULT_RETRIEVAL, min_confidence=0.60)),
        ("no filter", replace(DEFAULT_RETRIEVAL, use_metadata_filter=False)),
    ]


def test_configs_are_immutable():
    """Frozen, so a layer deep in the call chain cannot edit a config mid-run.

    A config is passed from app.py through glassbox into the recommender and the
    retriever. If any of them could mutate it, the number the Inspector reports
    and the number the pipeline used could differ, which is the one failure a
    glass box must never have.
    """
    with pytest.raises(FrozenInstanceError):
        DEFAULT_SCORING.genre_weight = 99.0
    with pytest.raises(FrozenInstanceError):
        DEFAULT_RETRIEVAL.use_metadata_filter = False


def test_helpers_resolve_none_to_the_defaults():
    """The None-means-defaults contract lives in one place and is checked there."""
    assert scoring_or_default(None) is DEFAULT_SCORING
    assert retrieval_or_default(None) is DEFAULT_RETRIEVAL

    custom = ScoringConfig(genre_weight=9.0)
    assert scoring_or_default(custom) is custom


def test_describe_names_only_what_changed():
    """The UI's configuration banner must not cry wolf on an unmodified run."""
    assert describe(DEFAULT_SCORING) == "defaults"
    assert describe(DEFAULT_RETRIEVAL) == "defaults"
    assert "genre_weight=3.0" in describe(replace(DEFAULT_SCORING, genre_weight=3.0))


def test_reset_returns_the_shipped_values():
    """The UI reset control cannot hand back anything but the defaults."""
    scoring, retrieval = reset_to_defaults()
    assert scoring == DEFAULT_SCORING
    assert retrieval == DEFAULT_RETRIEVAL


# ---------------------------------------------------------------------------
# 3. Each knob demonstrably moves a measurement
# ---------------------------------------------------------------------------

def test_scoring_weights_change_the_ranking_not_just_the_numbers():
    """A weight has to be able to reorder the list, or it is decoration.

    Zeroing the genre weight on a pop/happy profile should let a non-pop song
    that matches mood and energy climb over a pop song that does not.
    """
    songs = _catalog()
    prefs = {"favorite_genre": "pop", "favorite_mood": "happy", "target_energy": 0.80}

    default_order = [s["title"] for s, _sc, _r in recommend_songs(prefs, songs, k=10)]
    no_genre = replace(DEFAULT_SCORING, genre_weight=0.0)
    reweighted = [s["title"] for s, _sc, _r
                  in recommend_songs(prefs, songs, k=10, config=no_genre)]

    assert default_order != reweighted


def test_the_tiebreak_knob_moves_hit_at_one():
    """Turning the tiebreak off through the CONFIG degrades ranking exactly as
    turning it off through evaluate's own flag does.

    Both routes to the same behavior must agree. If they ever diverge, the
    comparison table (which drives everything from configs) would be measuring
    something different from the older two-call idiom the existing tests use.
    """
    songs, notes = _catalog(), _notes()
    no_tiebreak = replace(DEFAULT_RETRIEVAL, use_exact_title_tiebreak=False)

    via_config = evaluate(songs, notes, config=no_tiebreak)
    via_flag = evaluate(songs, notes, replace(DEFAULT_RETRIEVAL, use_exact_title_tiebreak=False))

    assert via_config == via_flag
    assert via_config["hit@1"] < evaluate(songs, notes)["hit@1"]


def test_the_floor_knob_moves_grounded_coverage_and_not_the_ranking():
    """Raising the floor refuses correct notes; it cannot improve retrieval.

    This is the distinction the comparison table exists to make visible. The
    floor acts after ranking, so a floor change that moved hit@1 would mean
    something is wired wrong.
    """
    songs, notes = _catalog(), _notes()
    high = replace(DEFAULT_RETRIEVAL, min_confidence=0.60)

    assert grounded_count(songs, notes, high) < grounded_count(songs, notes)
    assert evaluate(songs, notes, config=high)["hit@1"] == evaluate(songs, notes)["hit@1"]


def test_the_metadata_filter_knob_reintroduces_the_leak_when_disabled():
    """The break-it switch really does break it, and only leave-one-out sees it.

    Two assertions, and the second is the more important one. Disabling the
    filter leaks the entire catalog under leave-one-out, AND leaves every ranking
    metric at a perfect score. That is why the filter is pinned by a test instead
    of being trusted to show up in hit@1: on a complete corpus, no ranking metric
    can detect its absence.
    """
    songs, notes = _catalog(), _notes()
    no_filter = replace(DEFAULT_RETRIEVAL, use_metadata_filter=False)

    assert leave_one_out(songs, notes)["leaked"] == 0
    assert leave_one_out(songs, notes, no_filter)["leaked"] == len(songs)

    broken = metrics_for_config(songs, notes, no_filter)
    assert broken["hit@1"] == 1.0
    assert broken["grounded"] == len(songs)


def test_the_stopword_knob_moves_the_overlap_ranking():
    """The stopword knob is nearly inert here, and the test pins WHY not just THAT.

    Measured, disabling stopword filtering moves only the overlap-only MRR, and
    only by one song's rank. That is a real finding rather than a disappointing
    one: _similarity divides by the QUERY tokens and counts only shared ones, and
    the query is title + genre + mood, which contains a stopword for just 3 of 46
    songs. So this test asserts the small change is real (a knob wired to nothing
    would show zero) while documenting that the effect is small for a reason.

    If someone later switches to natural-language queries, this knob becomes
    dominant and this test should start failing loudly on the magnitude.
    """
    songs, notes = _catalog(), _notes()
    no_stopwords = replace(DEFAULT_RETRIEVAL, use_stopwords=False)

    with_sw = evaluate(songs, notes, replace(DEFAULT_RETRIEVAL, use_exact_title_tiebreak=False))
    without_sw = evaluate(songs, notes, replace(no_stopwords, use_exact_title_tiebreak=False))

    assert without_sw["mrr"] < with_sw["mrr"]
    # The exact-title tiebreak is strong enough to hide this entirely, which is
    # the reason the comparison table carries a separate overlap-only column.
    assert evaluate(songs, notes, config=no_stopwords)["hit@1"] == 1.0


# ---------------------------------------------------------------------------
# 4. The UI must never write back to the defaults
# ---------------------------------------------------------------------------
#
# These read app.py as TEXT rather than importing it. Driving Streamlit widgets
# headlessly needs a script runner and a session context, which would make these
# slow and flaky for no gain: the property being protected ("this source file
# does not contain an assignment to the shipped defaults") is a property of the
# source, so checking the source directly is both the cheapest and the most
# honest way to check it.

APP_PY = os.path.join(os.path.dirname(__file__), "..", "app.py")


def _app_source() -> str:
    with open(APP_PY, encoding="utf-8") as f:
        return f.read()


def test_the_ui_never_assigns_to_the_shipped_defaults():
    """Runtime-only means runtime-only: no path from a slider to src/config.py.

    The defaults are what the graded claims rest on, so a UI that could edit them
    would let a stray slider invalidate the write-ups with no failing test and no
    visible symptom. Both objects are frozen, so an assignment would raise at
    runtime, but only if that code path were exercised: a reset branch nobody
    clicks during review would sit there broken and unnoticed. This catches it
    without needing the branch to run.

    Implemented over the AST rather than by substring search, because app.py
    legitimately READS the defaults all over the knob panel (every widget takes
    its `value=` from them). A text search for "DEFAULT_SCORING." cannot tell a
    read from a write; the parse tree can, by looking only at assignment targets.
    """
    import ast

    protected = {"DEFAULT_SCORING", "DEFAULT_RETRIEVAL"}
    offenders = []

    for node in ast.walk(ast.parse(_app_source())):
        if isinstance(node, (ast.Assign, ast.AugAssign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                # Rebinding the name itself: DEFAULT_SCORING = ...
                if isinstance(target, ast.Name) and target.id in protected:
                    offenders.append(f"line {node.lineno}: rebinds {target.id}")
                # Mutating a field: DEFAULT_SCORING.genre_weight = ...
                if (isinstance(target, ast.Attribute)
                        and isinstance(target.value, ast.Name)
                        and target.value.id in protected):
                    offenders.append(
                        f"line {node.lineno}: writes {target.value.id}.{target.attr}")

    assert not offenders, "app.py writes to the shipped defaults: " + "; ".join(offenders)


def test_the_ui_does_not_persist_the_knobs_to_disk():
    """No file writing in the UI at all, which is the blunt version of the rule.

    A knob panel that saved a preferences file would be a reasonable feature in
    another project and is forbidden here, because "the defaults are what the
    documentation describes" stops being true the moment a run can be
    reconfigured by something left on disk from a previous session.
    """
    source = _app_source()
    for forbidden in ("open(", "json.dump", "yaml.dump", ".write_text(", ".to_csv("):
        assert forbidden not in source, f"app.py appears to write state via {forbidden!r}"


def test_every_knob_widget_is_covered_by_the_reset_control():
    """Reset must clear EVERY knob, including one added later.

    _reset_knobs works by deleting session_state keys, so a knob whose key was
    never added to _KNOB_KEYS would survive a reset and silently keep applying.
    The user would see "Reset to defaults", believe it, and read the resulting
    numbers as the shipped system's. This compares the declared list against the
    keys actually used in the file so the two cannot drift.
    """
    import re

    source = _app_source()

    declared = set(re.findall(r'"(knob_\w+)"', source.split("def _knob_controls")[0]))
    used = set(re.findall(r'key="(knob_\w+)"', source))

    assert used, "no knob widgets found; did the keys get renamed?"
    assert used == declared, (
        f"reset list and widget keys disagree. "
        f"only in widgets: {used - declared}, only in reset list: {declared - used}"
    )


def test_the_comparison_table_renders_every_variant():
    """The deliverable itself: --compare must produce a row per configuration."""
    table = render_comparison(_catalog(), _notes())

    for label in ("defaults (shipped)", "no exact-title tiebreak",
                  "no stopword filtering", "floor raised to 0.60",
                  "NO metadata filter (bug)"):
        assert label in table

    # The break-it row must be labelled as a bug wherever it appears, so a reader
    # skimming the table cannot mistake it for a tuning option.
    assert "bug" in table
